import type { ActivityInterface } from '@/interfaces/ActivityInterface.js';

export const activitySeeder: ActivityInterface[] = [
  {
    id: 1,
    userId: 1,
    name: 'Alimentación',
    color: '#EF4444',
    type: 'expense',
    targetAmount: 800000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 2,
    userId: 1,
    name: 'Transporte',
    color: '#F97316',
    type: 'expense',
    targetAmount: 300000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 3,
    userId: 1,
    name: 'Salud',
    color: '#EC4899',
    type: 'expense',
    targetAmount: 200000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    userId: 1,
    name: 'Entretenimiento',
    color: '#A855F7',
    type: 'expense',
    targetAmount: 400000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    userId: 1,
    name: 'Servicios públicos',
    color: '#6366F1',
    type: 'expense',
    targetAmount: 250000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    userId: 1,
    name: 'Fondo de emergencias',
    color: '#22C55E',
    type: 'savings',
    targetAmount: 5000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    userId: 1,
    name: 'Vacaciones',
    color: '#14B8A6',
    type: 'savings',
    targetAmount: 3000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    userId: 2,
    name: 'Alimentación',
    color: '#10B981',
    type: 'expense',
    targetAmount: 400000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 9,
    userId: 2,
    name: 'Transporte',
    color: '#0EA5E9',
    type: 'expense',
    targetAmount: 150000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    userId: 2,
    name: 'Ocio',
    color: '#F59E0B',
    type: 'expense',
    targetAmount: 200000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    userId: 2,
    name: 'Salud',
    color: '#EC4899',
    type: 'expense',
    targetAmount: 100000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    userId: 2,
    name: 'Hogar',
    color: '#6366F1',
    type: 'expense',
    targetAmount: 600000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    userId: 2,
    name: 'Fondo emergencia',
    color: '#8B5CF6',
    type: 'savings',
    targetAmount: 6000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    userId: 2,
    name: 'Viaje Japón',
    color: '#14B8A6',
    type: 'savings',
    targetAmount: 5000000,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
