import type { TransactionInterface } from '@/interfaces/TransactionInterface.js';

export const transactionSeeder: TransactionInterface[] = [
  // --- February 2026 ---
  {
    id: 1,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 185000,
    date: '2026-02-03',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 2,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 72000,
    date: '2026-02-07',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 3,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 135000,
    date: '2026-02-10',
    description: 'Factura electricidad',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 4,
    accountId: 3,
    activityId: 6,
    type: 'expense',
    amount: 400000,
    date: '2026-02-15',
    description: 'Aporte fondo de emergencias',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 5,
    accountId: 1,
    activityId: 4,
    type: 'expense',
    amount: 65000,
    date: '2026-02-20',
    description: 'Streaming y apps',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- March 2026 ---
  {
    id: 6,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 210000,
    date: '2026-03-02',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 7,
    accountId: 2,
    activityId: 3,
    type: 'expense',
    amount: 55000,
    date: '2026-03-08',
    description: 'Cita médica',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 8,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 80000,
    date: '2026-03-14',
    description: 'Mantenimiento carro',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 9,
    accountId: 3,
    activityId: 7,
    type: 'expense',
    amount: 250000,
    date: '2026-03-16',
    description: 'Ahorro vacaciones diciembre',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 10,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 150000,
    date: '2026-03-20',
    description: 'Internet y teléfono',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- April 2026 ---
  {
    id: 11,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 195000,
    date: '2026-04-01',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 12,
    accountId: 4,
    activityId: 6,
    type: 'expense',
    amount: 800000,
    date: '2026-04-05',
    description: 'Aporte extra fondo emergencias',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 13,
    accountId: 2,
    activityId: 4,
    type: 'expense',
    amount: 120000,
    date: '2026-04-12',
    description: 'Concierto',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 14,
    accountId: 1,
    activityId: 3,
    type: 'expense',
    amount: 45000,
    date: '2026-04-18',
    description: 'Farmacia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 15,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 68000,
    date: '2026-04-22',
    description: 'Recarga tarjeta transporte',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- May 2026 ---
  {
    id: 16,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 220000,
    date: '2026-05-03',
    description: 'Mercado mensual completo',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 17,
    accountId: 3,
    activityId: 7,
    type: 'expense',
    amount: 300000,
    date: '2026-05-10',
    description: 'Ahorro vacaciones',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 18,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 140000,
    date: '2026-05-15',
    description: 'Servicios del mes',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 19,
    accountId: 2,
    activityId: 4,
    type: 'expense',
    amount: 90000,
    date: '2026-05-20',
    description: 'Cena con amigos',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 20,
    accountId: 4,
    activityId: 6,
    type: 'expense',
    amount: 600000,
    date: '2026-05-28',
    description: 'Transferencia inversión',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- June 2026 ---
  {
    id: 21,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 175000,
    date: '2026-06-04',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 22,
    accountId: 2,
    activityId: 3,
    type: 'expense',
    amount: 180000,
    date: '2026-06-09',
    description: 'Dentista',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 23,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 76000,
    date: '2026-06-15',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 24,
    accountId: 3,
    activityId: 6,
    type: 'expense',
    amount: 350000,
    date: '2026-06-20',
    description: 'Aporte mensual fondo',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 25,
    accountId: 1,
    activityId: 4,
    type: 'expense',
    amount: 55000,
    date: '2026-06-26',
    description: 'Plataformas digitales',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  // --- July 2026 ---
  {
    id: 26,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 205000,
    date: '2026-07-03',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 27,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 160000,
    date: '2026-07-10',
    description: 'Factura gas y agua',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 28,
    accountId: 3,
    activityId: 7,
    type: 'expense',
    amount: 500000,
    date: '2026-07-15',
    description: 'Ahorro vacaciones diciembre',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 29,
    accountId: 2,
    activityId: 4,
    type: 'expense',
    amount: 130000,
    date: '2026-07-21',
    description: 'Ropa y accesorios',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 30,
    accountId: 4,
    activityId: 6,
    type: 'expense',
    amount: 750000,
    date: '2026-07-29',
    description: 'Ahorro fin de año',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
    // --- August 2026 ---
  {
    id: 31,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 230000,
    date: '2026-08-03',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 32,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 145000,
    date: '2026-08-08',
    description: 'Servicios públicos',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 33,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 90000,
    date: '2026-08-14',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 34,
    accountId: 1,
    activityId: 1,
    type: 'income',
    amount: 2800000,
    date: '2026-08-15',
    description: 'Pago de nómina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 35,
    accountId: 3,
    activityId: 4,
    type: 'expense',
    amount: 110000,
    date: '2026-08-23',
    description: 'Salida con amigos',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- September 2026 ---
  {
    id: 36,
    accountId: 1,
    activityId: 1,
    type: 'income',
    amount: 3000000,
    date: '2026-09-01',
    description: 'Pago de nómina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 37,
    accountId: 1,
    activityId: 1,
    type: 'expense',
    amount: 250000,
    date: '2026-09-01',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 38,
    accountId: 2,
    activityId: 2,
    type: 'expense',
    amount: 85000,
    date: '2026-09-01',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 39,
    accountId: 1,
    activityId: 5,
    type: 'expense',
    amount: 170000,
    date: '2026-09-01',
    description: 'Internet y servicios',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 40,
    accountId: 3,
    activityId: 6,
    type: 'expense',
    amount: 400000,
    date: '2026-09-01',
    description: 'Ahorro del mes',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // ===========================================================
  // Usuario Demo (userId 2) — accounts 5-8, activities 8-14
  // ===========================================================

  // --- February 2026 ---
  {
    id: 41,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2200000,
    date: '2026-02-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 42,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 165000,
    date: '2026-02-04',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 43,
    accountId: 6,
    activityId: 9,
    type: 'expense',
    amount: 60000,
    date: '2026-02-09',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 44,
    accountId: 7,
    activityId: 13,
    type: 'expense',
    amount: 200000,
    date: '2026-02-14',
    description: 'Aporte fondo emergencia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 45,
    accountId: 5,
    activityId: 12,
    type: 'expense',
    amount: 90000,
    date: '2026-02-20',
    description: 'Factura servicios',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- March 2026 ---
  {
    id: 46,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2200000,
    date: '2026-03-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 47,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 180000,
    date: '2026-03-05',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 48,
    accountId: 6,
    activityId: 11,
    type: 'expense',
    amount: 45000,
    date: '2026-03-10',
    description: 'Farmacia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 49,
    accountId: 8,
    activityId: 10,
    type: 'expense',
    amount: 60000,
    date: '2026-03-15',
    description: 'Cine',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 50,
    accountId: 7,
    activityId: 14,
    type: 'expense',
    amount: 150000,
    date: '2026-03-22',
    description: 'Ahorro viaje Japón',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- April 2026 ---
  {
    id: 51,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2200000,
    date: '2026-04-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 52,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 190000,
    date: '2026-04-04',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 53,
    accountId: 6,
    activityId: 9,
    type: 'expense',
    amount: 55000,
    date: '2026-04-11',
    description: 'Recarga transporte',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 54,
    accountId: 7,
    activityId: 13,
    type: 'expense',
    amount: 250000,
    date: '2026-04-18',
    description: 'Aporte fondo emergencia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 55,
    accountId: 5,
    activityId: 12,
    type: 'expense',
    amount: 85000,
    date: '2026-04-24',
    description: 'Internet y teléfono',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- May 2026 ---
  {
    id: 56,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2300000,
    date: '2026-05-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 57,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 200000,
    date: '2026-05-05',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 58,
    accountId: 6,
    activityId: 11,
    type: 'expense',
    amount: 38000,
    date: '2026-05-12',
    description: 'Cita médica',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 59,
    accountId: 8,
    activityId: 10,
    type: 'expense',
    amount: 70000,
    date: '2026-05-18',
    description: 'Salida con amigos',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 60,
    accountId: 7,
    activityId: 14,
    type: 'expense',
    amount: 180000,
    date: '2026-05-25',
    description: 'Ahorro viaje Japón',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- June 2026 ---
  {
    id: 61,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2300000,
    date: '2026-06-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 62,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 175000,
    date: '2026-06-04',
    description: 'Mercado semanal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 63,
    accountId: 6,
    activityId: 9,
    type: 'expense',
    amount: 62000,
    date: '2026-06-10',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 64,
    accountId: 7,
    activityId: 13,
    type: 'expense',
    amount: 300000,
    date: '2026-06-16',
    description: 'Aporte fondo emergencia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 65,
    accountId: 5,
    activityId: 12,
    type: 'expense',
    amount: 95000,
    date: '2026-06-23',
    description: 'Servicios del mes',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- July 2026 ---
  {
    id: 66,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2300000,
    date: '2026-07-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 67,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 210000,
    date: '2026-07-05',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 68,
    accountId: 8,
    activityId: 10,
    type: 'expense',
    amount: 65000,
    date: '2026-07-12',
    description: 'Cine y cena',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 69,
    accountId: 6,
    activityId: 11,
    type: 'expense',
    amount: 50000,
    date: '2026-07-19',
    description: 'Farmacia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 70,
    accountId: 7,
    activityId: 14,
    type: 'expense',
    amount: 200000,
    date: '2026-07-27',
    description: 'Ahorro viaje Japón',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- August 2026 ---
  {
    id: 71,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2400000,
    date: '2026-08-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 72,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 220000,
    date: '2026-08-04',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 73,
    accountId: 6,
    activityId: 9,
    type: 'expense',
    amount: 58000,
    date: '2026-08-11',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 74,
    accountId: 7,
    activityId: 13,
    type: 'expense',
    amount: 350000,
    date: '2026-08-17',
    description: 'Aporte fondo emergencia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 75,
    accountId: 5,
    activityId: 12,
    type: 'expense',
    amount: 100000,
    date: '2026-08-24',
    description: 'Internet y servicios',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // --- September 2026 ---
  {
    id: 76,
    accountId: 5,
    activityId: 8,
    type: 'income',
    amount: 2400000,
    date: '2026-09-01',
    description: 'Salario mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 77,
    accountId: 5,
    activityId: 8,
    type: 'expense',
    amount: 230000,
    date: '2026-09-01',
    description: 'Mercado mensual',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 78,
    accountId: 6,
    activityId: 9,
    type: 'expense',
    amount: 65000,
    date: '2026-09-01',
    description: 'Gasolina',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 79,
    accountId: 7,
    activityId: 13,
    type: 'expense',
    amount: 400000,
    date: '2026-09-01',
    description: 'Aporte fondo emergencia',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 80,
    accountId: 8,
    activityId: 10,
    type: 'expense',
    amount: 80000,
    date: '2026-09-01',
    description: 'Salida con amigos',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
