// External imports
import type { MigrationInterface, QueryRunner } from 'typeorm';

// Demo data that lived in the frontend seeders during Deliverable 1. The
// passwords are scrypt hashes (PasswordHasher of @nestjs/authentication) of the
// demo credentials shown on the sign-in page
// (admin123 / user123).
const USERS = [
  {
    id: 1,
    name: 'Admin Demo',
    email: 'admin@finzen.app',
    password:
      '$scrypt$ln=17,r=8,p=1$rb/YaKF2CoCcLEjotINosg$w8p7PxydmOu3xnKGF6+Zt4pkGGclpeONEOW/zH+2TqU',
    role: 'admin',
    active: true,
  },
  {
    id: 2,
    name: 'Usuario Demo',
    email: 'user@finzen.app',
    password:
      '$scrypt$ln=17,r=8,p=1$pHW4DDKek1In5nKK/R48vw$ezbynXVQYqe3aOUP4KBYJJNCCiUgL3GQZjzhSoTENTA',
    role: 'user',
    active: true,
  },
];

const ACCOUNTS = [
  { id: 1, name: 'Bancolombia', type: 'Ahorros', balance: 5000000, userId: 1 },
  { id: 2, name: 'Davivienda', type: 'Corriente', balance: 2500000, userId: 1 },
  { id: 3, name: 'Nequi', type: 'Ahorros', balance: 3000000, userId: 1 },
  { id: 4, name: 'Banco de Bogotá', type: 'Inversión', balance: 10000000, userId: 1 },
  { id: 5, name: 'Bancolombia', type: 'Ahorros', balance: 1200000, userId: 2 },
  { id: 6, name: 'Davivienda', type: 'Corriente', balance: 1000000, userId: 2 },
  { id: 7, name: 'Nequi', type: 'Digital', balance: 2600000, userId: 2 },
  { id: 8, name: 'Efectivo', type: 'Efectivo', balance: 800000, userId: 2 },
];

const ACTIVITIES = [
  {
    id: 1,
    name: 'Alimentación',
    color: '#EF4444',
    type: 'expense',
    targetAmount: 800000,
    userId: 1,
  },
  { id: 2, name: 'Transporte', color: '#F97316', type: 'expense', targetAmount: 300000, userId: 1 },
  { id: 3, name: 'Salud', color: '#EC4899', type: 'expense', targetAmount: 200000, userId: 1 },
  {
    id: 4,
    name: 'Entretenimiento',
    color: '#A855F7',
    type: 'expense',
    targetAmount: 400000,
    userId: 1,
  },
  {
    id: 5,
    name: 'Servicios públicos',
    color: '#6366F1',
    type: 'expense',
    targetAmount: 250000,
    userId: 1,
  },
  {
    id: 6,
    name: 'Fondo de emergencias',
    color: '#22C55E',
    type: 'savings',
    targetAmount: 5000000,
    userId: 1,
  },
  {
    id: 7,
    name: 'Vacaciones',
    color: '#14B8A6',
    type: 'savings',
    targetAmount: 3000000,
    userId: 1,
  },
  {
    id: 8,
    name: 'Alimentación',
    color: '#10B981',
    type: 'expense',
    targetAmount: 400000,
    userId: 2,
  },
  { id: 9, name: 'Transporte', color: '#0EA5E9', type: 'expense', targetAmount: 150000, userId: 2 },
  { id: 10, name: 'Ocio', color: '#F59E0B', type: 'expense', targetAmount: 200000, userId: 2 },
  { id: 11, name: 'Salud', color: '#EC4899', type: 'expense', targetAmount: 100000, userId: 2 },
  { id: 12, name: 'Hogar', color: '#6366F1', type: 'expense', targetAmount: 600000, userId: 2 },
  {
    id: 13,
    name: 'Fondo emergencia',
    color: '#8B5CF6',
    type: 'savings',
    targetAmount: 6000000,
    userId: 2,
  },
  {
    id: 14,
    name: 'Viaje Japón',
    color: '#14B8A6',
    type: 'savings',
    targetAmount: 5000000,
    userId: 2,
  },
];

const TRANSACTIONS = [
  {
    id: 1,
    type: 'expense',
    amount: 185000,
    date: '2026-02-03',
    description: 'Mercado semanal',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 2,
    type: 'expense',
    amount: 72000,
    date: '2026-02-07',
    description: 'Gasolina',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 3,
    type: 'expense',
    amount: 135000,
    date: '2026-02-10',
    description: 'Factura electricidad',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 4,
    type: 'expense',
    amount: 400000,
    date: '2026-02-15',
    description: 'Aporte fondo de emergencias',
    accountId: 3,
    activityId: 6,
  },
  {
    id: 5,
    type: 'expense',
    amount: 65000,
    date: '2026-02-20',
    description: 'Streaming y apps',
    accountId: 1,
    activityId: 4,
  },
  {
    id: 6,
    type: 'expense',
    amount: 210000,
    date: '2026-03-02',
    description: 'Mercado mensual',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 7,
    type: 'expense',
    amount: 55000,
    date: '2026-03-08',
    description: 'Cita médica',
    accountId: 2,
    activityId: 3,
  },
  {
    id: 8,
    type: 'expense',
    amount: 80000,
    date: '2026-03-14',
    description: 'Mantenimiento carro',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 9,
    type: 'expense',
    amount: 250000,
    date: '2026-03-16',
    description: 'Ahorro vacaciones diciembre',
    accountId: 3,
    activityId: 7,
  },
  {
    id: 10,
    type: 'expense',
    amount: 150000,
    date: '2026-03-20',
    description: 'Internet y teléfono',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 11,
    type: 'expense',
    amount: 195000,
    date: '2026-04-01',
    description: 'Mercado semanal',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 12,
    type: 'expense',
    amount: 800000,
    date: '2026-04-05',
    description: 'Aporte extra fondo emergencias',
    accountId: 4,
    activityId: 6,
  },
  {
    id: 13,
    type: 'expense',
    amount: 120000,
    date: '2026-04-12',
    description: 'Concierto',
    accountId: 2,
    activityId: 4,
  },
  {
    id: 14,
    type: 'expense',
    amount: 45000,
    date: '2026-04-18',
    description: 'Farmacia',
    accountId: 1,
    activityId: 3,
  },
  {
    id: 15,
    type: 'expense',
    amount: 68000,
    date: '2026-04-22',
    description: 'Recarga tarjeta transporte',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 16,
    type: 'expense',
    amount: 220000,
    date: '2026-05-03',
    description: 'Mercado mensual completo',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 17,
    type: 'expense',
    amount: 300000,
    date: '2026-05-10',
    description: 'Ahorro vacaciones',
    accountId: 3,
    activityId: 7,
  },
  {
    id: 18,
    type: 'expense',
    amount: 140000,
    date: '2026-05-15',
    description: 'Servicios del mes',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 19,
    type: 'expense',
    amount: 90000,
    date: '2026-05-20',
    description: 'Cena con amigos',
    accountId: 2,
    activityId: 4,
  },
  {
    id: 20,
    type: 'expense',
    amount: 600000,
    date: '2026-05-28',
    description: 'Transferencia inversión',
    accountId: 4,
    activityId: 6,
  },
  {
    id: 21,
    type: 'expense',
    amount: 175000,
    date: '2026-06-04',
    description: 'Mercado semanal',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 22,
    type: 'expense',
    amount: 180000,
    date: '2026-06-09',
    description: 'Dentista',
    accountId: 2,
    activityId: 3,
  },
  {
    id: 23,
    type: 'expense',
    amount: 76000,
    date: '2026-06-15',
    description: 'Gasolina',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 24,
    type: 'expense',
    amount: 350000,
    date: '2026-06-20',
    description: 'Aporte mensual fondo',
    accountId: 3,
    activityId: 6,
  },
  {
    id: 25,
    type: 'expense',
    amount: 55000,
    date: '2026-06-26',
    description: 'Plataformas digitales',
    accountId: 1,
    activityId: 4,
  },
  {
    id: 26,
    type: 'expense',
    amount: 205000,
    date: '2026-07-03',
    description: 'Mercado mensual',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 27,
    type: 'expense',
    amount: 160000,
    date: '2026-07-10',
    description: 'Factura gas y agua',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 28,
    type: 'expense',
    amount: 500000,
    date: '2026-07-15',
    description: 'Ahorro vacaciones diciembre',
    accountId: 3,
    activityId: 7,
  },
  {
    id: 29,
    type: 'expense',
    amount: 130000,
    date: '2026-07-21',
    description: 'Ropa y accesorios',
    accountId: 2,
    activityId: 4,
  },
  {
    id: 30,
    type: 'expense',
    amount: 750000,
    date: '2026-07-29',
    description: 'Ahorro fin de año',
    accountId: 4,
    activityId: 6,
  },
  {
    id: 31,
    type: 'expense',
    amount: 230000,
    date: '2026-08-03',
    description: 'Mercado mensual',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 32,
    type: 'expense',
    amount: 145000,
    date: '2026-08-08',
    description: 'Servicios públicos',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 33,
    type: 'expense',
    amount: 90000,
    date: '2026-08-14',
    description: 'Gasolina',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 34,
    type: 'income',
    amount: 2800000,
    date: '2026-08-15',
    description: 'Pago de nómina',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 35,
    type: 'expense',
    amount: 110000,
    date: '2026-08-23',
    description: 'Salida con amigos',
    accountId: 3,
    activityId: 4,
  },
  {
    id: 36,
    type: 'income',
    amount: 3000000,
    date: '2026-09-01',
    description: 'Pago de nómina',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 37,
    type: 'expense',
    amount: 250000,
    date: '2026-09-01',
    description: 'Mercado mensual',
    accountId: 1,
    activityId: 1,
  },
  {
    id: 38,
    type: 'expense',
    amount: 85000,
    date: '2026-09-01',
    description: 'Gasolina',
    accountId: 2,
    activityId: 2,
  },
  {
    id: 39,
    type: 'expense',
    amount: 170000,
    date: '2026-09-01',
    description: 'Internet y servicios',
    accountId: 1,
    activityId: 5,
  },
  {
    id: 40,
    type: 'expense',
    amount: 400000,
    date: '2026-09-01',
    description: 'Ahorro del mes',
    accountId: 3,
    activityId: 6,
  },
  {
    id: 41,
    type: 'income',
    amount: 2200000,
    date: '2026-02-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 42,
    type: 'expense',
    amount: 165000,
    date: '2026-02-04',
    description: 'Mercado semanal',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 43,
    type: 'expense',
    amount: 60000,
    date: '2026-02-09',
    description: 'Gasolina',
    accountId: 6,
    activityId: 9,
  },
  {
    id: 44,
    type: 'expense',
    amount: 200000,
    date: '2026-02-14',
    description: 'Aporte fondo emergencia',
    accountId: 7,
    activityId: 13,
  },
  {
    id: 45,
    type: 'expense',
    amount: 90000,
    date: '2026-02-20',
    description: 'Factura servicios',
    accountId: 5,
    activityId: 12,
  },
  {
    id: 46,
    type: 'income',
    amount: 2200000,
    date: '2026-03-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 47,
    type: 'expense',
    amount: 180000,
    date: '2026-03-05',
    description: 'Mercado mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 48,
    type: 'expense',
    amount: 45000,
    date: '2026-03-10',
    description: 'Farmacia',
    accountId: 6,
    activityId: 11,
  },
  {
    id: 49,
    type: 'expense',
    amount: 60000,
    date: '2026-03-15',
    description: 'Cine',
    accountId: 8,
    activityId: 10,
  },
  {
    id: 50,
    type: 'expense',
    amount: 150000,
    date: '2026-03-22',
    description: 'Ahorro viaje Japón',
    accountId: 7,
    activityId: 14,
  },
  {
    id: 51,
    type: 'income',
    amount: 2200000,
    date: '2026-04-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 52,
    type: 'expense',
    amount: 190000,
    date: '2026-04-04',
    description: 'Mercado semanal',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 53,
    type: 'expense',
    amount: 55000,
    date: '2026-04-11',
    description: 'Recarga transporte',
    accountId: 6,
    activityId: 9,
  },
  {
    id: 54,
    type: 'expense',
    amount: 250000,
    date: '2026-04-18',
    description: 'Aporte fondo emergencia',
    accountId: 7,
    activityId: 13,
  },
  {
    id: 55,
    type: 'expense',
    amount: 85000,
    date: '2026-04-24',
    description: 'Internet y teléfono',
    accountId: 5,
    activityId: 12,
  },
  {
    id: 56,
    type: 'income',
    amount: 2300000,
    date: '2026-05-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 57,
    type: 'expense',
    amount: 200000,
    date: '2026-05-05',
    description: 'Mercado mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 58,
    type: 'expense',
    amount: 38000,
    date: '2026-05-12',
    description: 'Cita médica',
    accountId: 6,
    activityId: 11,
  },
  {
    id: 59,
    type: 'expense',
    amount: 70000,
    date: '2026-05-18',
    description: 'Salida con amigos',
    accountId: 8,
    activityId: 10,
  },
  {
    id: 60,
    type: 'expense',
    amount: 180000,
    date: '2026-05-25',
    description: 'Ahorro viaje Japón',
    accountId: 7,
    activityId: 14,
  },
  {
    id: 61,
    type: 'income',
    amount: 2300000,
    date: '2026-06-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 62,
    type: 'expense',
    amount: 175000,
    date: '2026-06-04',
    description: 'Mercado semanal',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 63,
    type: 'expense',
    amount: 62000,
    date: '2026-06-10',
    description: 'Gasolina',
    accountId: 6,
    activityId: 9,
  },
  {
    id: 64,
    type: 'expense',
    amount: 300000,
    date: '2026-06-16',
    description: 'Aporte fondo emergencia',
    accountId: 7,
    activityId: 13,
  },
  {
    id: 65,
    type: 'expense',
    amount: 95000,
    date: '2026-06-23',
    description: 'Servicios del mes',
    accountId: 5,
    activityId: 12,
  },
  {
    id: 66,
    type: 'income',
    amount: 2300000,
    date: '2026-07-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 67,
    type: 'expense',
    amount: 210000,
    date: '2026-07-05',
    description: 'Mercado mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 68,
    type: 'expense',
    amount: 65000,
    date: '2026-07-12',
    description: 'Cine y cena',
    accountId: 8,
    activityId: 10,
  },
  {
    id: 69,
    type: 'expense',
    amount: 50000,
    date: '2026-07-19',
    description: 'Farmacia',
    accountId: 6,
    activityId: 11,
  },
  {
    id: 70,
    type: 'expense',
    amount: 200000,
    date: '2026-07-27',
    description: 'Ahorro viaje Japón',
    accountId: 7,
    activityId: 14,
  },
  {
    id: 71,
    type: 'income',
    amount: 2400000,
    date: '2026-08-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 72,
    type: 'expense',
    amount: 220000,
    date: '2026-08-04',
    description: 'Mercado mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 73,
    type: 'expense',
    amount: 58000,
    date: '2026-08-11',
    description: 'Gasolina',
    accountId: 6,
    activityId: 9,
  },
  {
    id: 74,
    type: 'expense',
    amount: 350000,
    date: '2026-08-17',
    description: 'Aporte fondo emergencia',
    accountId: 7,
    activityId: 13,
  },
  {
    id: 75,
    type: 'expense',
    amount: 100000,
    date: '2026-08-24',
    description: 'Internet y servicios',
    accountId: 5,
    activityId: 12,
  },
  {
    id: 76,
    type: 'income',
    amount: 2400000,
    date: '2026-09-01',
    description: 'Salario mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 77,
    type: 'expense',
    amount: 230000,
    date: '2026-09-01',
    description: 'Mercado mensual',
    accountId: 5,
    activityId: 8,
  },
  {
    id: 78,
    type: 'expense',
    amount: 65000,
    date: '2026-09-01',
    description: 'Gasolina',
    accountId: 6,
    activityId: 9,
  },
  {
    id: 79,
    type: 'expense',
    amount: 400000,
    date: '2026-09-01',
    description: 'Aporte fondo emergencia',
    accountId: 7,
    activityId: 13,
  },
  {
    id: 80,
    type: 'expense',
    amount: 80000,
    date: '2026-09-01',
    description: 'Salida con amigos',
    accountId: 8,
    activityId: 10,
  },
];

// Exports
export class SeedDemoData1790716122982 implements MigrationInterface {
  name = 'SeedDemoData1790716122982';

  public async up(queryRunner: QueryRunner): Promise<void> {
    for (const user of USERS) {
      await queryRunner.query(
        'INSERT INTO "user" ("id", "name", "email", "password", "role", "active") VALUES (?, ?, ?, ?, ?, ?)',
        [user.id, user.name, user.email, user.password, user.role, user.active ? 1 : 0],
      );
    }

    for (const account of ACCOUNTS) {
      await queryRunner.query(
        'INSERT INTO "account" ("id", "name", "type", "balance", "userId") VALUES (?, ?, ?, ?, ?)',
        [account.id, account.name, account.type, account.balance, account.userId],
      );
    }

    for (const activity of ACTIVITIES) {
      await queryRunner.query(
        'INSERT INTO "activity" ("id", "name", "color", "type", "targetAmount", "userId") VALUES (?, ?, ?, ?, ?, ?)',
        [
          activity.id,
          activity.name,
          activity.color,
          activity.type,
          activity.targetAmount,
          activity.userId,
        ],
      );
    }

    for (const transaction of TRANSACTIONS) {
      await queryRunner.query(
        'INSERT INTO "transaction" ("id", "type", "amount", "date", "description", "accountId", "activityId") VALUES (?, ?, ?, ?, ?, ?, ?)',
        [
          transaction.id,
          transaction.type,
          transaction.amount,
          transaction.date,
          transaction.description,
          transaction.accountId,
          transaction.activityId,
        ],
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query('DELETE FROM "transaction"');
    await queryRunner.query('DELETE FROM "activity"');
    await queryRunner.query('DELETE FROM "account"');
    await queryRunner.query('DELETE FROM "user"');
  }
}
