import type { TransactionInterface } from '@/interfaces/TransactionInterface';

export const transactionSeeder: TransactionInterface[] = [
  // --- February 2026 ---
  {
    id: 'txn-01',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 185000,
    date: '2026-02-03',
    description: 'Mercado semanal',
  },
  {
    id: 'txn-02',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-2',
    type: 'expense',
    amount: 72000,
    date: '2026-02-07',
    description: 'Gasolina',
  },
  {
    id: 'txn-03',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-5',
    type: 'expense',
    amount: 135000,
    date: '2026-02-10',
    description: 'Factura electricidad',
  },
  {
    id: 'txn-04',
    userId: '1',
    accountId: 'acc-3',
    activityId: 'act-6',
    type: 'savings',
    amount: 400000,
    date: '2026-02-15',
    description: 'Aporte fondo de emergencias',
  },
  {
    id: 'txn-05',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-4',
    type: 'expense',
    amount: 65000,
    date: '2026-02-20',
    description: 'Streaming y apps',
  },
  // --- March 2026 ---
  {
    id: 'txn-06',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 210000,
    date: '2026-03-02',
    description: 'Mercado mensual',
  },
  {
    id: 'txn-07',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-3',
    type: 'expense',
    amount: 55000,
    date: '2026-03-08',
    description: 'Cita médica',
  },
  {
    id: 'txn-08',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-2',
    type: 'expense',
    amount: 80000,
    date: '2026-03-14',
    description: 'Mantenimiento carro',
  },
  {
    id: 'txn-09',
    userId: '1',
    accountId: 'acc-3',
    activityId: 'act-7',
    type: 'savings',
    amount: 250000,
    date: '2026-03-16',
    description: 'Ahorro vacaciones diciembre',
  },
  {
    id: 'txn-10',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-5',
    type: 'expense',
    amount: 150000,
    date: '2026-03-20',
    description: 'Internet y teléfono',
  },
  // --- April 2026 ---
  {
    id: 'txn-11',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 195000,
    date: '2026-04-01',
    description: 'Mercado semanal',
  },
  {
    id: 'txn-12',
    userId: '1',
    accountId: 'acc-4',
    activityId: 'act-6',
    type: 'savings',
    amount: 800000,
    date: '2026-04-05',
    description: 'Aporte extra fondo emergencias',
  },
  {
    id: 'txn-13',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-4',
    type: 'expense',
    amount: 120000,
    date: '2026-04-12',
    description: 'Concierto',
  },
  {
    id: 'txn-14',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-3',
    type: 'expense',
    amount: 45000,
    date: '2026-04-18',
    description: 'Farmacia',
  },
  {
    id: 'txn-15',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-2',
    type: 'expense',
    amount: 68000,
    date: '2026-04-22',
    description: 'Recarga tarjeta transporte',
  },
  // --- May 2026 ---
  {
    id: 'txn-16',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 220000,
    date: '2026-05-03',
    description: 'Mercado mensual completo',
  },
  {
    id: 'txn-17',
    userId: '1',
    accountId: 'acc-3',
    activityId: 'act-7',
    type: 'savings',
    amount: 300000,
    date: '2026-05-10',
    description: 'Ahorro vacaciones',
  },
  {
    id: 'txn-18',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-5',
    type: 'expense',
    amount: 140000,
    date: '2026-05-15',
    description: 'Servicios del mes',
  },
  {
    id: 'txn-19',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-4',
    type: 'expense',
    amount: 90000,
    date: '2026-05-20',
    description: 'Cena con amigos',
  },
  {
    id: 'txn-20',
    userId: '1',
    accountId: 'acc-4',
    activityId: 'act-6',
    type: 'savings',
    amount: 600000,
    date: '2026-05-28',
    description: 'Transferencia inversión',
  },
  // --- June 2026 ---
  {
    id: 'txn-21',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 175000,
    date: '2026-06-04',
    description: 'Mercado semanal',
  },
  {
    id: 'txn-22',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-3',
    type: 'expense',
    amount: 180000,
    date: '2026-06-09',
    description: 'Dentista',
  },
  {
    id: 'txn-23',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-2',
    type: 'expense',
    amount: 76000,
    date: '2026-06-15',
    description: 'Gasolina',
  },
  {
    id: 'txn-24',
    userId: '1',
    accountId: 'acc-3',
    activityId: 'act-6',
    type: 'savings',
    amount: 350000,
    date: '2026-06-20',
    description: 'Aporte mensual fondo',
  },
  {
    id: 'txn-25',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-4',
    type: 'expense',
    amount: 55000,
    date: '2026-06-26',
    description: 'Plataformas digitales',
  },
  // --- July 2026 ---
  {
    id: 'txn-26',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-1',
    type: 'expense',
    amount: 205000,
    date: '2026-07-03',
    description: 'Mercado mensual',
  },
  {
    id: 'txn-27',
    userId: '1',
    accountId: 'acc-1',
    activityId: 'act-5',
    type: 'expense',
    amount: 160000,
    date: '2026-07-10',
    description: 'Factura gas y agua',
  },
  {
    id: 'txn-28',
    userId: '1',
    accountId: 'acc-3',
    activityId: 'act-7',
    type: 'savings',
    amount: 500000,
    date: '2026-07-15',
    description: 'Ahorro vacaciones diciembre',
  },
  {
    id: 'txn-29',
    userId: '1',
    accountId: 'acc-2',
    activityId: 'act-4',
    type: 'expense',
    amount: 130000,
    date: '2026-07-21',
    description: 'Ropa y accesorios',
  },
  {
    id: 'txn-30',
    userId: '1',
    accountId: 'acc-4',
    activityId: 'act-6',
    type: 'savings',
    amount: 750000,
    date: '2026-07-29',
    description: 'Ahorro fin de año',
  },
];
